# Generated by Django 4.1.7 on 2023-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('l_name', models.CharField(max_length=255, unique=True, verbose_name='نام\u200cخانوادگی')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('amount', models.PositiveBigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دریافتی',
                'verbose_name_plural': 'دریافتی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(blank=True, max_length=6, null=True, verbose_name='پیگیری')),
                ('time', models.CharField(blank=True, max_length=5, null=True, verbose_name='زمان')),
                ('date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ')),
                ('atm_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='شماره ترمینال')),
                ('recovery', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره بازیابی')),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('from_accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_accounts', to='financial.account', verbose_name='از حساب')),
                ('to_accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_accounts', to='financial.account', verbose_name='به حساب')),
            ],
            options={
                'verbose_name': 'قبض',
                'verbose_name_plural': 'قبوض',
            },
        ),
    ]
