# Generated by Django 4.1.7 on 2023-03-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='f_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='account',
            name='l_name',
            field=models.CharField(max_length=255, verbose_name='نام\u200cخانوادگی'),
        ),
    ]
