# Generated by Django 4.1.7 on 2023-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام')),
                ('l_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام\u200cخانوادگی')),
                ('job', models.CharField(blank=True, max_length=128, null=True, verbose_name='شغل')),
                ('tell', models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن')),
                ('brand_name', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='نام تولیدی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('payment_card', models.ForeignKey(blank=True, max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.account', verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
    ]
