# Generated by Django 4.1.7 on 2023-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('1', 'Free'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1, null=True, verbose_name='سایز')),
                ('model_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام مدل')),
                ('total_taqe', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل طاقه\u200cها')),
                ('total_taqe_khar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد طاقه\u200cهای خرجکار')),
                ('masraf_per_car', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مصرف هر کار')),
                ('length_khat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طول خط\u200cکشی')),
                ('code', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='کد برش')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('type_parche', models.CharField(blank=True, max_length=128, null=True, verbose_name='جنس پارچه')),
                ('total_car', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل کارها')),
                ('total_ply', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل لاها')),
                ('brand_name', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut_brand_name', to='users.user', verbose_name='نام تولیدی')),
                ('tailor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tailor', to='users.user', verbose_name='خیاط')),
            ],
            options={
                'verbose_name': 'برش',
                'verbose_name_plural': 'برش\u200cها',
            },
        ),
    ]
