# Generated by Django 4.1.7 on 2023-04-28 13:24

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('workhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='masraf_lai_per_car',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='مصرف لایی هر کار'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
