# Generated by Django 4.1.7 on 2023-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhouse', '0002_cut_masraf_lai_per_car_alter_cut_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='model_code',
            field=models.CharField(
                blank=True, default='undf', max_length=4, null=True, verbose_name='کد برش'),
        ),
    ]
