# Generated by Django 4.1.7 on 2023-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhouse', '0004_alter_cut_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='model_code',
            field=models.CharField(blank=True, default='undefined', max_length=4, null=True, verbose_name='کد برش'),
        ),
    ]
