# Generated by Django 4.1.7 on 2023-04-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhouse', '0007_alter_cut_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='کد برش'),
        ),
    ]
