# Generated by Django 4.1.7 on 2023-03-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='حتما وارد شود', max_length=128, verbose_name='رنگ')),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='طول')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('ply_car', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد لا')),
                ('total_car', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کار')),
                ('ply_khar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد لای خرجکار')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('cut_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='workhouse.cut', verbose_name='کد برش')),
            ],
            options={
                'verbose_name': 'طاقه',
                'verbose_name_plural': 'طاقه\u200cها',
            },
        ),
    ]
